name: Build and Test Program

on:
  workflow_call:

jobs:
  # TODO build Program
  # TODO run tests
  build_test:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
