name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  GH_TOKEN: ${{ github.token }}
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release & Merge
    runs-on: ubuntu-latest
    # needs: [build_test]
    steps:
      - uses: actions/checkout@v4
      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.42.1

      - name: Extract Project Version
        run: echo "PROJECT_VERSION=$(yq '.package.version' $PWD/Cargo.toml)" >> $GITHUB_ENV

      - name: Check existing tags
        run: |
          # TODO ?? Guard against case CHANGELOG hasn't changed since previous release
          if [[ $(git tag -l $PROJECT_VERSION) ]]; 
          then
            echo "Release $PROJECT_VERSION already exists. Please increment package version in Cargo.toml"
            exit 1
          else
            echo "Tagging release $PROJECT_VERSION"
            git tag -a "v$PROJECT_VERSION" -F ./CHANGELOG.md
            # TODO push to remote
          fi

      # TODO Merge_PR pending fresh approval of changes
      - name: Merge PR
        run: |
          echo "Merging PR"
          # TODO Uncomment me when ready
          # gh pr merge --auto -d

  build_test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose --release

      - name: Run tests
        run: cargo test --verbose
