name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  GH_TOKEN: ${{ github.token }}
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.42.1

      - name: Merge PR
        run: |
          # TODO Get list of releases
          # TODO Get version from cargo.toml
          # TODO if version already exists in releases; exit 1
          # TODO else gh create release $version
          #
          echo $(yq ".package.version" $PWD/Cargo.toml)
          echo "Merge PR" 
          echo $(gh label list)

  # TODO Build_Test
  build_test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose --release

      - name: Run tests
        run: cargo test --verbose

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build_test]

    steps:
      - uses: actions/checkout@v4
      # TODO Validate project version++
      - name: Get project version
        run: echo "Get version"

      # TODO Release Version increase required to deploy a change to code
      - name: Tag release with package version
        run: echo "Tag release version"

      # TODO Merge_PR pending fresh approval of changes
      - name: Merge PR
        run: |
          echo "Merge PR" 
          # echo $(gh pr merge --auto -d)
